import ForgotPasswordWrapper from "@/components/AuthControl/ForgotPasswordWrapper";
import { type NextPage } from "next";
import Head from "next/head";

const ForgotPassword: NextPage = () => {
  return (
    <>
      <Head>
        <title>HallOfFame</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"></main> */}
      <ForgotPasswordWrapper />
      {/* helloworld */}
    </>
  );
};

export default ForgotPassword;
