import LoginWrapper from "@/components/AuthControl/LoginWrapper";
import { type NextPage } from "next";
import Head from "next/head";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>HallOfFame</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginWrapper />
    </>
  );
};

export default Login;
