import DashWrapper from "@/components/Dashboard/DashWrapper";
import { getServerAuthSession } from "@/server/auth";
import { api } from "@/utils/api";
import { type GetServerSideProps } from "next";
import { type NextPage } from "next";
import Head from "next/head";
import { useAtom } from "jotai";
import { userAtom } from "@/jotai/user";
import { useEffect } from "react";

const Home: NextPage<{ data: string }> = ({ data }) => {
  const [user, setUser] = useAtom(userAtom);
  const getUserDetails = api.user.getUserProfilePhoto.useQuery({
    email: data,
  });

  useEffect(() => {
    if (getUserDetails.isSuccess && getUserDetails.data) {
      setUser(getUserDetails.data);
    }
  }, [getUserDetails.data, getUserDetails.isSuccess, setUser]);

  return (
    <>
      <Head>
        <title>HallOfFame</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashWrapper />
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const data = await getServerAuthSession(context);
  if (data?.user.email) {
    return {
      props: {
        data: data.user.email,
      },
    };
  } else {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }
};
